
DROP TABLE dbo.Test_Harness_Notify

	 
CREATE TABLE Test_Harness_Notify (
	 ID INT NOT NULL IDENTITY
	 ,EVENT_TYPE VARCHAR(20)
	 ,CLIENT_REF VARCHAR(50)
	 ,TX_STATE VARCHAR(20)
	 ,TX_ID VARCHAR(50)
	 ,AMOUNT VARCHAR(20)
	 ,HASH VARCHAR(200)
	 PRIMARY KEY (ID)

)
