DROP TABLE IF EXISTS Test_Harness_Notify;
DROP TABLE IF EXISTS Test_Harness_WPCallback;
	 
	CREATE TABLE Test_Harness_Notify (
	 ID INT NOT NULL AUTO_INCREMENT
	 ,EVENT_TYPE VARCHAR(20)
	 ,CLIENT_REF VARCHAR(50)
	 ,TX_STATE VARCHAR(20)
	 ,TX_ID VARCHAR(50)
	 ,AMOUNT VARCHAR(20)
	 ,HASH VARCHAR(200)
	);
	
	CREATE TABLE Test_Harness_WPCallback(
		ID INT NOT NULL AUTO_INCREMENT
	 	,PARAMS VARCHAR(5000)
	 	,HEADERS VARCHAR(5000)
	 	,NOWDATE VARCHAR(20)
	);